// Contoh daftar 77 cara share
const waysToShare = [
    "Share on Twitter",
    "Post on Instagram",
    "Make a TikTok video",
    "Write a blog post",
    "Create a YouTube video",
    "Share in Telegram groups",
    "Invite friends to platform",
    "Join community events",
    "Share memes about Virtualizer",
    "Create fan art",
    "Host a Twitter Space",
    "Post on Reddit",
    "Share on Facebook",
    "Pin on Pinterest",
    "Create a LinkedIn post",
    "Make an infographic",
    "Start a podcast episode",
    "Send an email newsletter",
    "Add Virtualizer to your signature",
    "Participate in AMAs",
    "Share success stories",
    "Collaborate with influencers",
    "Create tutorials",
    "Organize a giveaway",
    "Make stickers",
    "Post in Discord servers",
    "Write reviews",
    "Host webinars",
    "Translate content",
    "Design merch",
    "Use hashtags",
    "Create challenges",
    "Share achievements",
    "Share news articles",
    "Write guides",
    "Create polls",
    "Share testimonials",
    "Host virtual meetups",
    "Make animation clips",
    "Create GIFs",
    "Post on Medium",
    "Use QR codes",
    "Add to newsletters",
    "Send invites to friends",
    "Share on Snapchat",
    "Create artwork",
    "Participate in competitions",
    "Write press releases",
    "Create stickers for WhatsApp",
    "Share in forums",
    "Record voice notes",
    "Make desktop wallpapers",
    "Make mobile wallpapers",
    "Create fan videos",
    "Host live streams",
    "Post in niche communities",
    "Create memes",
    "Design social templates",
    "Record tutorials",
    "Share on TikTok trends",
    "Post on Discord",
    "Share via email",
    "Join crypto communities",
    "Translate website content",
    "Host challenges",
    "Share your story",
    "Post screenshots",
    "Create comics",
    "Make music remixes",
    "Participate in hackathons",
    "Give talks",
    "Write newsletters",
    "Create mini-games",
    "Share stickers",
    "Post in chat groups",
    "Make tutorial videos",
    "Share tips and tricks",
    "Create fan pages",
    "Collaborate with creators",
    "Organize contests",
    "Share on blogs",
    "Make short clips"
];

// Render list in HTML
const listElement = document.getElementById("share-list");

waysToShare.forEach((way, index) => {
    const li = document.createElement("li");
    li.textContent = `${index + 1}. ${way}`;
    listElement.appendChild(li);
});
